version: '3.9'

services:
    mysql-nbd-db:
        image: mysql
        restart: always
        volumes:
          - ./storage:/var/lib/mysql
          - ./scripts:/docker-entrypoint-initdb.d
        environment:
          - MYSQL_ROOT_PASSWORD=my-secret-pw
        ports:
          - "49153:3306"

